Feature/docker compose
reciplease/reciplease pull request #36
Opened 2020-05-25 20:29 UTC by VikashKothary

2020-07-06 08:00 UTC, rhys-saldanha commented
will this need to change to PostgreSQL?

2020-07-06 08:01 UTC, rhys-saldanha reviewed
I'm not great at reviewing PRs on Github

2020-07-06 08:01 UTC, rhys-saldanha requested changes
PostgreSQL?

2021-01-02 23:40 UTC, closed without merging

2021-01-02 23:40 UTC, VikashKothary commented
Closed because it's no longer necessary.