feat: Separate business logic and database implementation details
reciplease/reciplease pull request #88
Opened 2022-01-09 18:38 UTC by VikashKothary

2022-01-14 23:03 UTC, rhys-saldanha requested changes

2022-01-14 23:03 UTC, rhys-saldanha commented on modules/core/src/main/java/org/reciplease/repository/IngredientRepository.java
>      List<Ingredient> findByNameContains(String searchName);
Can we rename to `searchByName` please

2022-01-14 23:03 UTC, rhys-saldanha commented on modules/core/src/main/java/org/reciplease/repository/InventoryRepository.java
>      List<InventoryItem> findByExpirationIsGreaterThanEqual(LocalDate now);
Another clunky name, maybe `expiresAfter`?

2022-01-14 23:03 UTC, rhys-saldanha commented on modules/core/src/main/java/org/reciplease/repository/PlannedRecipeRepository.java
>      List<PlannedRecipe> findByDateIsBetween(LocalDate start, LocalDate end);
`betweenDates`

2022-01-14 23:03 UTC, rhys-saldanha commented on modules/core/src/main/java/org/reciplease/repository/RecipeRepository.java
> +    Optional<Recipe> findByUuid(final UUID uuid);
All the other repositories use ID over UUID, need to pick one for consistency. I prefer this.

2022-01-14 23:03 UTC, rhys-saldanha commented on modules/database/src/main/java/org/reciplease/model/BaseEntity.java
>  import io.swagger.v3.oas.annotations.media.Schema;
Hibernate entities don't need OAS annotations, I'm not happy that this package is even accessible in the database module.

2022-01-14 23:03 UTC, rhys-saldanha commented on modules/parent/pom.xml
> +        <kotlin.version>1.6.10</kotlin.version>
nice

2022-01-14 23:03 UTC, rhys-saldanha commented on modules/web/src/main/java/org/reciplease/dto/IngredientDto.java
> +    @Nullable
Is it?...

2022-01-14 23:03 UTC, rhys-saldanha commented
Code coverage is a bit lacking 😞

2022-01-16 18:25 UTC, VikashKothary commented on modules/core/src/main/java/org/reciplease/repository/IngredientRepository.java
>      List<Ingredient> findByNameContains(String searchName);
Done.

2022-01-16 18:32 UTC, VikashKothary commented on modules/core/src/main/java/org/reciplease/repository/InventoryRepository.java
>      List<InventoryItem> findByExpirationIsGreaterThanEqual(LocalDate now);
Done.

2022-01-16 19:24 UTC, VikashKothary commented on modules/parent/pom.xml
> +        <kotlin.version>1.6.10</kotlin.version>
:P

2022-01-16 19:25 UTC, VikashKothary commented on modules/web/src/main/java/org/reciplease/dto/IngredientDto.java
> +    @Nullable
No idea, so I'll just remove the annotation.

2022-01-16 19:27 UTC, VikashKothary commented on modules/core/src/main/java/org/reciplease/repository/PlannedRecipeRepository.java
>      List<PlannedRecipe> findByDateIsBetween(LocalDate start, LocalDate end);
Done.

2022-01-16 19:28 UTC, VikashKothary commented
We can definitely improve the code coverage, I'm just concerned how chunky this PR is becoming.

2022-01-16 19:31 UTC, VikashKothary commented on modules/core/src/main/java/org/reciplease/repository/RecipeRepository.java
> +    Optional<Recipe> findByUuid(final UUID uuid);
Totally agree. Done.

2022-03-10 16:02 UTC, merged